language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t danifmarquess/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true danifmarquess/docker-react npm run test

  
